[package]
name = "p19"
version = "0.1.0"
authors = ["Marvin Gudel <marvin.s.gudel@studmail.w-hs.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bmp = "0.5.0"
matrix = "0.22.0"
simple-matrix = "0.1"