[package]
name = "p10"
version = "0.1.0"
authors = ["Marvin Gudel <marvin.s.gudel@studmail.w-hs.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.3"
wav = "0.5"
